name = "tgbot-d1"
main = "TGbot-D1创新版本2.6.2.js"
compatibility_date = "2024-01-01"

# 变量配置：直接在这里定义，绕过网页端保存失败的问题
[vars]
BOT_TOKEN = "8414802664:AAHxdVnHs1RgbPrqPOMKLcMRMUHhf9j3_Nw"
ADMIN_IDS = "787641992"
ADMIN_GROUP_ID = "-1003472135984"

# 数据库绑定配置
[[d1_databases]]
binding = "TG_BOT_DB"
database_name = "tg-bot-db"
database_id = "85ffe473-649b-44d6-8f55-fd0af1f894ca"
