name = "tgbot-d1"
main = "TGbot-D1创新版本2.6.2.js" # 注意：这里要指向作者仓库里的文件名
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "TG_BOT_DB"
database_name = "tg-bot-db"
database_id = "85ffe473-649b-44d6-8f55-fd0af1f894ca"
